booking:
  property: Booking Profile Dev Updated

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true